site_name: O:RE
theme:
  name: material
  palette:
    primary: white
    accent: light blue
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/gitlab
  language: kr
  features:
    - header.autohide
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables

nav:
  - About O:RE: index.md
  - ì‹œì‘í•˜ê¸°:
      - ğŸ§‘ğŸ»â€ğŸ’» ê´€ë¦¬ìí¸: for_owner.md
      - ğŸ™‹ğŸ» ì‚¬ìš©ìí¸: for_user.md
  - O:RE ì²´í—˜í•´ë³´ê¸°: test.md
  - ê¸°ëŠ¥ í™•ì¥ì„ ìœ„í•œ ê°€ì´ë“œ: extension.md

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://lab.ssafy.com/s07-final/S07P31A504.git
    - icon: fontawesome/solid/paper-plane
      link: mailto:<oreofficialcontact@naver.com>

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2022 SSAFY 7ê¸° ë§ˆì§€ë§‰ììƒˆ
