site_name: O:RE
theme: 
  name: material
nav:
  - Home: index.md
  - ì‹œì‘í•˜ê¸°- ğŸ’»ê´€ë¦¬ìí¸: for_owner.md
  - ì‹œì‘í•˜ê¸°- ğŸ™‹ğŸ»ì‚¬ìš©ìí¸: for_user.md
  - O:RE ì²´í—˜í•´ë³´ê¸°: test.md

extra_css:
  - stylesheets/extra.css